{{- if .Values.backend.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qtodo.backend.fullname" . }}-secret
  labels:
    {{- include "qtodo.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.backend.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.betterAuthSecret }}
  BETTER_AUTH_SECRET: {{ .Values.backend.secrets.betterAuthSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.groqApiKey }}
  GROQ_API_KEY: {{ .Values.backend.secrets.groqApiKey | b64enc | quote }}
  {{- end }}
{{- end }}
