{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qtodo.frontend.fullname" . }}-config
  labels:
    {{- include "qtodo.frontend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.frontend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
